--   ==========================================================================
--       V1__Create_Initial_Schema.sql
--       Criação inicial de tabelas, sequências e constraints
--   ==========================================================================

-- 0. CONFIGURAÇÃO DO SCHEMA
CREATE SCHEMA IF NOT EXISTS agrolog;
SET search_path TO agrolog;

-- 1. SEQUENCES
CREATE SEQUENCE seq_company START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_carrier START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_branch START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_users START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_schedule START WITH 1 INCREMENT BY 1;

-- 2. TABELA COMPANY
CREATE TABLE company (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq_company'),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    name VARCHAR(255) NOT NULL UNIQUE,
    cnpj VARCHAR(20) UNIQUE
);

-- 3. TABELA CARRIER
CREATE TABLE carrier (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq_carrier'),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- 4. TABELA BRANCH
CREATE TABLE branch (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq_branch'),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    name VARCHAR(255) NOT NULL UNIQUE,
    address VARCHAR(255),
    code VARCHAR(50),
    company_id BIGINT NOT NULL,
    CONSTRAINT fk_branch_company FOREIGN KEY (company_id) REFERENCES company(id)
);

-- 5. TABELA USERS
CREATE TABLE users (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq_users'),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    name VARCHAR(255),
    username VARCHAR(255) UNIQUE,
    cpf VARCHAR(14) UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    role VARCHAR(50) NOT NULL,
    branch_id BIGINT,
    company_id BIGINT,
    carrier_id BIGINT,
    CONSTRAINT fk_users_branch FOREIGN KEY (branch_id) REFERENCES branch(id),
    CONSTRAINT fk_users_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT fk_users_carrier FOREIGN KEY (carrier_id) REFERENCES carrier(id)
);

-- 6. TABELA SCHEDULE
CREATE TABLE schedule (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq_schedule'),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    version BIGINT,
    branch_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    carrier_id BIGINT,
    grain_type VARCHAR(50) NOT NULL,
    operation_type VARCHAR(50) NOT NULL,
    truck_type VARCHAR(50) NOT NULL,
    license_plate VARCHAR(20) NOT NULL,
    queue_status VARCHAR(50) NOT NULL,
    queue_position INTEGER,
    called_at TIMESTAMP,
    released_at TIMESTAMP,
    CONSTRAINT fk_schedule_branch FOREIGN KEY (branch_id) REFERENCES branch(id),
    CONSTRAINT fk_schedule_driver FOREIGN KEY (driver_id) REFERENCES users(id),
    CONSTRAINT fk_schedule_carrier FOREIGN KEY (carrier_id) REFERENCES carrier(id)
);

-- 7. TABELA SCHEDULE_HISTORY
CREATE TABLE schedule_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    previous_status VARCHAR(50),
    new_status VARCHAR(50) NOT NULL,
    changed_by_user_id BIGINT NOT NULL,
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_history_schedule FOREIGN KEY (schedule_id) REFERENCES schedule(id) ON DELETE CASCADE,
    CONSTRAINT fk_history_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id)
);

-- Índices adicionais para performance
CREATE INDEX idx_schedule_branch_status ON schedule(branch_id, queue_status);
CREATE INDEX idx_schedule_plate ON schedule(license_plate);